services:
  api:
    build:
      dockerfile: ./.infra/Dockerfile
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - '8000:8000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres_s1:
    image: postgres:latest
    ports:
      - "6433:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_s1:/var/lib/postgresql/data

  postgres_s2:
    image: postgres:latest
    ports:
      - "7434:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_s2:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
  postgres_s1:
    driver: local
  postgres_s2:
    driver: local
