services:
  api:
    build:
      dockerfile: ./.deploy/Dockerfile
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    network_mode: host
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis-1:
    container_name: "redis-1"
    image: redis:6.0-alpine
    ports:
      - 7000:7000
      - 17000:17000
    volumes:
      - "./.infra/local/services/redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7000
    network_mode: "host"
  redis-2:
    container_name: "redis-2"
    image: redis:6.0-alpine
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - "./.infra/local/services/redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7001
    network_mode: "host"
  redis-3:
    container_name: "redis-3"
    image: redis:6.0-alpine
    ports:
      - 7002:7002
      - 17002:17002
    volumes:
      - "./.infra/local/services/redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7002
    network_mode: "host"
  redis-4:
    container_name: "redis-4"
    image: redis:6.0-alpine
    ports:
      - 7003:7003
      - 17003:17003
    volumes:
      - "./.infra/local/services/redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7003
    network_mode: "host"
  redis-5:
    container_name: "redis-5"
    image: redis:6.0-alpine
    ports:
      - 7004:7004
      - 17004:17004
    volumes:
      - "./.infra/local/services/redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7004
    network_mode: "host"
  redis-6:
    container_name: "redis-6"
    image: redis:6.0-alpine
    ports:
      - 7005:7005
      - 17005:17005
    volumes:
      - "./.infra/local/services/redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7005
    network_mode: "host"


volumes:
  postgres:
    driver: local
